---
locale: en
tags: []
layout: input_bottom
editor: code
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: true
progressive_expectations: false
choices: []
name: Let's kick the beat
