---
locale: en
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`mystery_operation` is a function, because it returns something"
  checked: true
- value: "`mystery_operation` is a procedure, because it returns nothing"
  checked: false
- value: "`mystery_operation` visits each element of `elements`, and increments `count`
    by `1` for each one"
  checked: true
- value: "`mystery_operation` initializes a local variable `count` to `0`"
  checked: true
- value: "`mystery_operation` initializes a global variable `count` to `0`"
  checked: false
- value: "`mystery_operation` does the same thing as the `len` function"
  checked: true
- value: "`mystery_operation` does not use the `item` variable"
  checked: true
name: We count on you
